config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    resources :accounts
  end

  resources :accounts, only: [:show] do
    resources :websites
  end

  resources :websites do
    resources :keywords
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :websites
  validates :name, presence: true
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :website
  has_many :positions, dependent: :destroy

  after_save :check_position

  # private

  def check_position
    positions.create(rank: hit_google(website.url, phrase))
  end

  def hit_google(website, keyword)
    conn = Faraday.get("https://www.googleapis.com/customsearch/v1?q=#{keyword}&cx=#{ENV['secret_google_cx']}&key=#{ENV['secret_google_key']}")
    p conn.status
    if conn.status == 200
      response = JSON.parse(conn.body)['items']
      return 'Error! Nothing found' if response.blank?
      p links = response.map {|item| URI.parse(item['link']).host}
      links.find_index(URI.parse(website).host) || 'Not in the first 10'
    else
      'Please try again later'
    end
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :keywordoo

  def formatted_rank
    /\A\d+\z/.match(rank) ? rank.to_i+1 : rank
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email,:first_name, :last_name, :password, :password_confirmation, presence: true
  validates :password, length: { minimum: 6 }
  before_save :upcase_credentials

  has_many :accounts

  private

  def upcase_credentials
    [first_name, last_name].map(&:capitalize!)
  end
end

app/models/website.rb
class Website < ActiveRecord::Base
  belongs_to :account
  has_many :keywords
  validates :name, :url, presence: true
  validate :check_url

  def check_url
    errors.add(:url, 'I cannot connect to this URL') unless check_status < 400
  end

  def check_status
    self.url = "http://#{url}" unless url[/\Ahttp:\/\//] || url[/\Ahttps:\/\//]
    begin
      Faraday.head(url).status
    rescue Faraday::Error::ConnectionFailed
      500
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def new
    @account = Account.new
  end

  def create
    @account = current_user.accounts.build(account_params)
    if @account.save
      redirect_to root_path, flash: {success: 'New account added'}
    else
      flash[:error] = 'Name cannot be blank'
      render 'new'
    end
  end

  def show
  end

  def index
  end

  private

  def account_params
    params.require(:account).permit(:name)
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def new
  end

  def create
    @website = Website.find(params[:website_id])
    @keyword = @website.keywords.create(keyword_params)
    if @keyword.save
      redirect_to account_website_path(@website.account, @website)
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def show
  end

  def destroy
    Keyword.find(params[:id]).destroy
    @website = Website.find(params[:website_id])
    redirect_to account_website_path(@website.account, @website), flash: {alert: 'Keyword deleted'}
  end

  private

  def keyword_params
    params.require(:keyword).permit(:phrase)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where('first_name = ? AND last_name = ?', user_params[:first_name], user_params[:last_name]).take
    if user && user.authenticate(user_params[:password])
      login(user)
      redirect_to root_path, flash: { success: 'Successfully logged in' }
    else
      flash.now[:error] = 'Invalid user / password'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path, flash: {notice: 'Succesfully logged out'}
  end

  private

  def user_params
    params.require(:session).permit(:first_name, :last_name, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:new, :create, :index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to root_path, flash: { notice: 'User successfully created' }
    else
      flash.now[:error] = 'Cannot save user'
      render 'new'
    end
  end

  def index
    @accounts = current_user.try(:accounts)
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end

  def authenticate_user
    redirect_to login_path, flash: { error: 'You need to sign in.' } if current_user.id != params[:id].to_i
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :authorize_account_owner
  def new
    @website = Website.new
  end

  def create
    @website = Website.new(websites_params)
    @website.account_id = params[:account_id]
    if @website.save
      redirect_to account_websites_path, flash: {success: 'Website added'}
    else
      flash.now[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @keyword = Keyword.new
    @website = Website.includes(:keywords).find(params[:id])
    # @keywords = @website.keywords
  end

  def index
    @account = Account.find(params[:account_id])
    @websites = @account.websites
  end

  private

  def websites_params
    params.require(:website).permit(:name, :url, :account_id)
  end

  def authorize_account_owner
    render plain: 'not authorized' unless current_user == Account.find(params[:account_id]).user
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
   { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
 end

 def flash_messages(opts = {})
   flash.each do |msg_type, message|
     concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
       concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
         concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
         concat content_tag(:span, 'Close', class: 'sr-only')
       end)
       concat message
     end)
   end
   nil
 end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !session[:user_id].nil?
  end

  def logout
    session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/accounts/_index.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-4">
    <%- if @accounts.any? %>
      <h4>Your accounts:</h4>
      
      <%- @accounts.each do |a| %>
        <h4><%= link_to a.name, account_websites_path(a) %></h4>
      <% end %>
    <% end %>

    <%= link_to 'Add new account', new_user_account_path(current_user), class: 'btn btn-default' %>
  </div>
</div>

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/new.html.erb
<h1>Accounts#new</h1>
<%= form_for(@account, url: user_accounts_path, method: :post)  do |a| %>
  <%= a.text_field :name %>
  <%= a.button :submit %>
<% end %>

app/views/accounts/show.html.erb
<h1>Account</h1>

app/views/keywords/create.html.erb
<h1>Keywords#create</h1>
<p>Find me in app/views/keywords/create.html.erb</p>

app/views/keywords/new.html.erb
<h1>Keywords#new</h1>
<p>Find me in app/views/keywords/new.html.erb</p>

app/views/keywords/show.html.erb
<h1>Keywords#show</h1>
<p>Find me in app/views/keywords/show.html.erb</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to 'Website Position', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%-if user_signed_in?%>
          <li><%=link_to 'Dashboard', current_user %></li>
          <li><%=link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
          <li><%=link_to 'Login', login_path %></li>
          <li><%=link_to 'Register', new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebsitePosition</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation'%>
<div class='container'>
  <%= flash_messages %>
  <%= yield %>
</div>
</body>
</html>

app/views/users/index.html.erb
<%- if user_signed_in? %>
  <h4><%= current_user.first_name %>'s dashboard</h4>
  <%= render 'accounts/index' %>
<% else  %>
<div class="row">
  <div class="col-md-3 col-md-offset-4">
    <h3>Sign in</h3>
    <%= render 'sessions/form' %>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-4">
    <h1> Add new user </h1>
    <%= simple_form_for @user do |f| %>
        <%= f.input :email %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :password %>
        <%= f.input :password_confirmation %>
        <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h4><%=" #{@user.first_name}'s dashboard'"%></h4>
<%= user_signed_in? %>

app/views/websites/index.html.erb
<h2>Websites you're monitoring:</h2>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name:</th>
      <th>Url:</th>
      <th>Current status:</th>
      <th>Go:</th>
    </tr>
  </thead>
<tbody>
<%- @websites.each do |w| %>
  <tr>
    <td><%=w.name%></td>
    <td><%=w.url %></td>
    <td><%= w.check_status %></td>
    <td><%=link_to 'Check position', account_website_path(@account, w), class: 'btn btn-default' %></td>
  </tr>
<% end %>
</tbody>
</table>

<%=link_to 'Add new website', new_account_website_path(params[:account_id]), class: 'btn btn-default' %>

app/views/websites/new.html.erb
<h1>Add new website</h1>
<%= simple_form_for(@website, url: account_websites_path, method: :post) do |w| %>
  <%= w.input :name %>
  <%= w.input :url %>
  <%= w.button :submit %>
<% end %>

app/views/websites/show.html.erb
<div class="row">
  <div class="col-md-7 col-md-offset-1">
    <h3><%=@website.name%></h3>
    <hr>
    <table class='table table-striped'>
      <thead>
        <tr>
          <th>Phrase</th>
          <th>Current google position</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        <%- @website.keywords.each do |p| %>
          <tr>
            <td><%= p.phrase %></td>
            <td><%= p.positions.last.try(:formatted_rank) %></td>
            <td><%=link_to 'Destroy', website_keyword_path(@website, p), method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <hr>
    <%= simple_form_for(@keyword, url: website_keywords_path(@website), method: :post) do |k| %>
      <%= k.input :phrase %>
      <%= k.button :submit, 'Add phrase' %>
    <% end %>

  </div>
</div>